### ISSUE TITLE
Download link doesn't work

### ISSUE THREAD

**Issue by Bogatinovski** [catarinaribeir0/queries-tpch-dbgen-mysql#1]
Hi, the download link doesn't work: [Please check it](http://www.tpc.org/tpch/spec/tpch_2_16_0.zipl)
Is there a new download link ?

**Comment by Lucasark** [comment]
http://www.tpc.org/tpc_documents_current_versions/download_programs/tools-download-request.asp?bm_type=TPC-H&bm_vers=2.17.3&mode=CURRENT-ONLY
